### ISSUE TITLE
Error: no non-missing arguments to min; returning InfError in strt:stp : result would be too long a vector

### ISSUE THREAD

**Issue by KevinAvilesRodriguez** [zakrobinson/RLDNe#1]
I am running the example code with the provided dataset and I get the following error when running the readLDNE_tab() function 

Show in New Window
no non-missing arguments to min; returning InfError in strt:stp : result would be too long a vector

Codes used: 

library(RLDNe)

data("wgp_example")

head(wgp_example,2)

#So the structure of the data is loci freq, and columns of pop and inds 

# Data prep, first the data is shaped into a genepop_zlr and then output placeholders are created 
gp_file<-write_genepop_zlr(loci = wgp_example[,3:ncol(wgp_example)],pops = wgp_example$pop,ind.ids = wgp_example$ind_id,folder = "",filename ="genepop_output.txt",missingVal = NA,ncode = 2,diploid = T)

param_files<- NeV2_LDNe_create(input_file = gp_file$Output_File ,param_file = "Ne_params.txt" ,NE_out_file = "Ne_out.txt")

run_LDNe(LDNe_params = param_files$param_file)

Ne_estimates<-readLDNe_tab(path = param_files$Ne_out_tab)

**Comment by zakrobinson** [comment]
I'm quite sorry that I missed this issue. I used this package for chapter of my graduate project and then stopped keeping an eye on the repository. I've recently made major changes and which I hope will address your issues. 

Best regards, 
-Zak
