### ISSUE TITLE
Error when running RunLDNe

### ISSUE THREAD

**Issue by clorenzo1** [zakrobinson/RLDNe#2]
Hi there, 

I am running your example code which works fine. When I replace your example data with my real data which looks like this: 

![image](https://github.com/zakrobinson/RLDNe/assets/118922170/27a81e22-6368-41dc-af8a-ce34d4f698e5)

I keep getting the following error when running the command "runLDNe": 

run_LDNe(LDNe_params = param_files$param_file)
Method(s): LD

>>> Input 1: [./genepop_output.txt], GENEPOP format
Error in input file [./genepop_output.txt]

*** Number of data files = 0 ***
[1] "output file location was specified in param file"

I compared my genepop_output.txt file with the example and, aside from the size of each population, I do not see a formatting difference. Do you know why I get this error? 

Thanks in advance! 
Coral Diaz

**Comment by zakrobinson** [comment]
Hi Coral, 

I'm quite sorry that I failed to see this issue. I've recently made major changes to the package that would hopefully address the issues you flagged over a year ago.
